/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.parser;

import sc.node.*;
import sc.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTParentheseOuvrante(@SuppressWarnings("unused") TParentheseOuvrante node)
    {
        this.index = 0;
    }

    @Override
    public void caseTParentheseFermante(@SuppressWarnings("unused") TParentheseFermante node)
    {
        this.index = 1;
    }

    @Override
    public void caseTVirgule(@SuppressWarnings("unused") TVirgule node)
    {
        this.index = 2;
    }

    @Override
    public void caseTOu(@SuppressWarnings("unused") TOu node)
    {
        this.index = 3;
    }

    @Override
    public void caseTEt(@SuppressWarnings("unused") TEt node)
    {
        this.index = 4;
    }

    @Override
    public void caseTDivise(@SuppressWarnings("unused") TDivise node)
    {
        this.index = 5;
    }

    @Override
    public void caseTPointVergule(@SuppressWarnings("unused") TPointVergule node)
    {
        this.index = 6;
    }

    @Override
    public void caseTInferieur(@SuppressWarnings("unused") TInferieur node)
    {
        this.index = 7;
    }

    @Override
    public void caseTNon(@SuppressWarnings("unused") TNon node)
    {
        this.index = 8;
    }

    @Override
    public void caseTFois(@SuppressWarnings("unused") TFois node)
    {
        this.index = 9;
    }

    @Override
    public void caseTEgal(@SuppressWarnings("unused") TEgal node)
    {
        this.index = 10;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 11;
    }

    @Override
    public void caseTMoin(@SuppressWarnings("unused") TMoin node)
    {
        this.index = 12;
    }

    @Override
    public void caseTNombre(@SuppressWarnings("unused") TNombre node)
    {
        this.index = 13;
    }

    @Override
    public void caseTIdentif(@SuppressWarnings("unused") TIdentif node)
    {
        this.index = 14;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 15;
    }
}
