/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AAvecsinonInstopetern extends PInstopetern
{
    private TSi _si_;
    private PExp2 _exp2_;
    private TAlors _alors_;
    private PInstrbloc _instrbloc_;
    private PInstnonnull _instnonnull_;

    public AAvecsinonInstopetern()
    {
        // Constructor
    }

    public AAvecsinonInstopetern(
        @SuppressWarnings("hiding") TSi _si_,
        @SuppressWarnings("hiding") PExp2 _exp2_,
        @SuppressWarnings("hiding") TAlors _alors_,
        @SuppressWarnings("hiding") PInstrbloc _instrbloc_,
        @SuppressWarnings("hiding") PInstnonnull _instnonnull_)
    {
        // Constructor
        setSi(_si_);

        setExp2(_exp2_);

        setAlors(_alors_);

        setInstrbloc(_instrbloc_);

        setInstnonnull(_instnonnull_);

    }

    @Override
    public Object clone()
    {
        return new AAvecsinonInstopetern(
            cloneNode(this._si_),
            cloneNode(this._exp2_),
            cloneNode(this._alors_),
            cloneNode(this._instrbloc_),
            cloneNode(this._instnonnull_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAvecsinonInstopetern(this);
    }

    public TSi getSi()
    {
        return this._si_;
    }

    public void setSi(TSi node)
    {
        if(this._si_ != null)
        {
            this._si_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._si_ = node;
    }

    public PExp2 getExp2()
    {
        return this._exp2_;
    }

    public void setExp2(PExp2 node)
    {
        if(this._exp2_ != null)
        {
            this._exp2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp2_ = node;
    }

    public TAlors getAlors()
    {
        return this._alors_;
    }

    public void setAlors(TAlors node)
    {
        if(this._alors_ != null)
        {
            this._alors_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alors_ = node;
    }

    public PInstrbloc getInstrbloc()
    {
        return this._instrbloc_;
    }

    public void setInstrbloc(PInstrbloc node)
    {
        if(this._instrbloc_ != null)
        {
            this._instrbloc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instrbloc_ = node;
    }

    public PInstnonnull getInstnonnull()
    {
        return this._instnonnull_;
    }

    public void setInstnonnull(PInstnonnull node)
    {
        if(this._instnonnull_ != null)
        {
            this._instnonnull_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instnonnull_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._si_)
            + toString(this._exp2_)
            + toString(this._alors_)
            + toString(this._instrbloc_)
            + toString(this._instnonnull_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._si_ == child)
        {
            this._si_ = null;
            return;
        }

        if(this._exp2_ == child)
        {
            this._exp2_ = null;
            return;
        }

        if(this._alors_ == child)
        {
            this._alors_ = null;
            return;
        }

        if(this._instrbloc_ == child)
        {
            this._instrbloc_ = null;
            return;
        }

        if(this._instnonnull_ == child)
        {
            this._instnonnull_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._si_ == oldChild)
        {
            setSi((TSi) newChild);
            return;
        }

        if(this._exp2_ == oldChild)
        {
            setExp2((PExp2) newChild);
            return;
        }

        if(this._alors_ == oldChild)
        {
            setAlors((TAlors) newChild);
            return;
        }

        if(this._instrbloc_ == oldChild)
        {
            setInstrbloc((PInstrbloc) newChild);
            return;
        }

        if(this._instnonnull_ == oldChild)
        {
            setInstnonnull((PInstnonnull) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
