/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstnonnullInstr extends PInstr
{
    private PInstnonnull _instnonnull_;

    public AInstnonnullInstr()
    {
        // Constructor
    }

    public AInstnonnullInstr(
        @SuppressWarnings("hiding") PInstnonnull _instnonnull_)
    {
        // Constructor
        setInstnonnull(_instnonnull_);

    }

    @Override
    public Object clone()
    {
        return new AInstnonnullInstr(
            cloneNode(this._instnonnull_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstnonnullInstr(this);
    }

    public PInstnonnull getInstnonnull()
    {
        return this._instnonnull_;
    }

    public void setInstnonnull(PInstnonnull node)
    {
        if(this._instnonnull_ != null)
        {
            this._instnonnull_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instnonnull_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instnonnull_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instnonnull_ == child)
        {
            this._instnonnull_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instnonnull_ == oldChild)
        {
            setInstnonnull((PInstnonnull) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
