/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ANonnullExp7 extends PExp7
{
    private TNonnull _nonnull_;
    private PExp7 _exp7_;

    public ANonnullExp7()
    {
        // Constructor
    }

    public ANonnullExp7(
        @SuppressWarnings("hiding") TNonnull _nonnull_,
        @SuppressWarnings("hiding") PExp7 _exp7_)
    {
        // Constructor
        setNonnull(_nonnull_);

        setExp7(_exp7_);

    }

    @Override
    public Object clone()
    {
        return new ANonnullExp7(
            cloneNode(this._nonnull_),
            cloneNode(this._exp7_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANonnullExp7(this);
    }

    public TNonnull getNonnull()
    {
        return this._nonnull_;
    }

    public void setNonnull(TNonnull node)
    {
        if(this._nonnull_ != null)
        {
            this._nonnull_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nonnull_ = node;
    }

    public PExp7 getExp7()
    {
        return this._exp7_;
    }

    public void setExp7(PExp7 node)
    {
        if(this._exp7_ != null)
        {
            this._exp7_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp7_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nonnull_)
            + toString(this._exp7_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nonnull_ == child)
        {
            this._nonnull_ = null;
            return;
        }

        if(this._exp7_ == child)
        {
            this._exp7_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nonnull_ == oldChild)
        {
            setNonnull((TNonnull) newChild);
            return;
        }

        if(this._exp7_ == oldChild)
        {
            setExp7((PExp7) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
