/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ANonnullExp6 extends PExp6
{
    private TNonnull _nonnull_;
    private PExp6 _exp6_;

    public ANonnullExp6()
    {
        // Constructor
    }

    public ANonnullExp6(
        @SuppressWarnings("hiding") TNonnull _nonnull_,
        @SuppressWarnings("hiding") PExp6 _exp6_)
    {
        // Constructor
        setNonnull(_nonnull_);

        setExp6(_exp6_);

    }

    @Override
    public Object clone()
    {
        return new ANonnullExp6(
            cloneNode(this._nonnull_),
            cloneNode(this._exp6_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANonnullExp6(this);
    }

    public TNonnull getNonnull()
    {
        return this._nonnull_;
    }

    public void setNonnull(TNonnull node)
    {
        if(this._nonnull_ != null)
        {
            this._nonnull_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nonnull_ = node;
    }

    public PExp6 getExp6()
    {
        return this._exp6_;
    }

    public void setExp6(PExp6 node)
    {
        if(this._exp6_ != null)
        {
            this._exp6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp6_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nonnull_)
            + toString(this._exp6_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nonnull_ == child)
        {
            this._nonnull_ = null;
            return;
        }

        if(this._exp6_ == child)
        {
            this._exp6_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nonnull_ == oldChild)
        {
            setNonnull((TNonnull) newChild);
            return;
        }

        if(this._exp6_ == oldChild)
        {
            setExp6((PExp6) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
