/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASanssinonInstopetern extends PInstopetern
{
    private TSi _si_;
    private PExp _exp_;
    private TNonnull _nonnull_;
    private TAlors _alors_;
    private PInstrbloc _instrbloc_;
    private PInstopetern _instopetern_;

    public ASanssinonInstopetern()
    {
        // Constructor
    }

    public ASanssinonInstopetern(
        @SuppressWarnings("hiding") TSi _si_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TNonnull _nonnull_,
        @SuppressWarnings("hiding") TAlors _alors_,
        @SuppressWarnings("hiding") PInstrbloc _instrbloc_,
        @SuppressWarnings("hiding") PInstopetern _instopetern_)
    {
        // Constructor
        setSi(_si_);

        setExp(_exp_);

        setNonnull(_nonnull_);

        setAlors(_alors_);

        setInstrbloc(_instrbloc_);

        setInstopetern(_instopetern_);

    }

    @Override
    public Object clone()
    {
        return new ASanssinonInstopetern(
            cloneNode(this._si_),
            cloneNode(this._exp_),
            cloneNode(this._nonnull_),
            cloneNode(this._alors_),
            cloneNode(this._instrbloc_),
            cloneNode(this._instopetern_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASanssinonInstopetern(this);
    }

    public TSi getSi()
    {
        return this._si_;
    }

    public void setSi(TSi node)
    {
        if(this._si_ != null)
        {
            this._si_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._si_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TNonnull getNonnull()
    {
        return this._nonnull_;
    }

    public void setNonnull(TNonnull node)
    {
        if(this._nonnull_ != null)
        {
            this._nonnull_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nonnull_ = node;
    }

    public TAlors getAlors()
    {
        return this._alors_;
    }

    public void setAlors(TAlors node)
    {
        if(this._alors_ != null)
        {
            this._alors_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alors_ = node;
    }

    public PInstrbloc getInstrbloc()
    {
        return this._instrbloc_;
    }

    public void setInstrbloc(PInstrbloc node)
    {
        if(this._instrbloc_ != null)
        {
            this._instrbloc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instrbloc_ = node;
    }

    public PInstopetern getInstopetern()
    {
        return this._instopetern_;
    }

    public void setInstopetern(PInstopetern node)
    {
        if(this._instopetern_ != null)
        {
            this._instopetern_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instopetern_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._si_)
            + toString(this._exp_)
            + toString(this._nonnull_)
            + toString(this._alors_)
            + toString(this._instrbloc_)
            + toString(this._instopetern_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._si_ == child)
        {
            this._si_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._nonnull_ == child)
        {
            this._nonnull_ = null;
            return;
        }

        if(this._alors_ == child)
        {
            this._alors_ = null;
            return;
        }

        if(this._instrbloc_ == child)
        {
            this._instrbloc_ = null;
            return;
        }

        if(this._instopetern_ == child)
        {
            this._instopetern_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._si_ == oldChild)
        {
            setSi((TSi) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._nonnull_ == oldChild)
        {
            setNonnull((TNonnull) newChild);
            return;
        }

        if(this._alors_ == oldChild)
        {
            setAlors((TAlors) newChild);
            return;
        }

        if(this._instrbloc_ == oldChild)
        {
            setInstrbloc((PInstrbloc) newChild);
            return;
        }

        if(this._instopetern_ == oldChild)
        {
            setInstopetern((PInstopetern) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
